title: Jeremy Fenwick
description: Jeremy Fenwick's project page. Focused on programming challenges.
baseurl: "" # leave empty for root
url: "https://jf.github.io"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme